# Generated by Django 4.2.2 on 2023-06-18 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos_maq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('horas_motor', models.CharField(max_length=50, verbose_name='Horimetro:')),
                ('imagem_maquina', models.ImageField(upload_to='thumb_maquinas')),
                ('padrinho', models.CharField(choices=[('Letra A', 'Letra A'), ('Letra B', 'Letra B'), ('Letra C', 'Letra C'), ('Letra D', 'Letra D')], default='Letra A', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_maquina', models.CharField(choices=[('F-HVE-0339', 'F-HVE-0339'), ('F-HVE-0341', 'F-HVE-0341'), ('F-HVE-0343', 'F-HVE-0343'), ('F-HVE-0347', 'F-HVE-0347'), ('F-HVE-0539', 'F-HVE-0539'), ('F-HVE-0540', 'F-HVE-0540'), ('F-HVE-0541', 'F-HVE-0541'), ('F-HVE-0542', 'F-HVE-0542'), ('F-HVE-0543', 'F-HVE-0543'), ('F-HVE-0544', 'F-HVE-0544')], default='Selecione', max_length=50, verbose_name='Repita a Maquina Selecionada:')),
                ('categoria', models.CharField(choices=[('maquina base', 'Maquina Base'), ('cabecote', 'Cabeça Processadora')], max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('corpo', models.TextField(max_length=1000)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('tempo_hora_homem', models.FloatField(default=1.0, max_length=100, verbose_name='Tempo Estimado de Manutenção (HH)')),
                ('status', models.CharField(choices=[('no prazo', 'No prazo'), ('vencido', 'Vencido'), ('concluido', 'Concluido')], max_length=100)),
                ('thumb', models.ImageField(default='default.jpg', upload_to='thumb_pendencias', verbose_name='Foto da Pendencia:')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='gestor.equipamentos_maq')),
            ],
        ),
        migrations.AddField(
            model_name='equipamentos_maq',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='gestor.instancia'),
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('ni', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('qtd', models.CharField(max_length=100)),
                ('preco_unit', models.CharField(max_length=100)),
                ('backlog', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='gestor.pendencias')),
            ],
        ),
    ]
