# Generated by Django 4.2.2 on 2023-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custo',
            name='preco_unit',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custo',
            name='qtd',
            field=models.IntegerField(max_length=100),
        ),
    ]
